use std::fs;
use std::path::Path;
use tokio::sync::mpsc;
use crate::installer::config::{LabConfig, EDA_LAUNCHER, VLSILAB_DIR};

pub async fn write_eda_launcher(
    config: &LabConfig,
    tx: mpsc::UnboundedSender<String>,
) -> Result<(), String> {
    send_log(&tx, "[INFO] Writing EDA Launcher wrapper script to /opt/vlsilab/eda-launcher.sh...");
    
    if let Err(e) = fs::create_dir_all(VLSILAB_DIR) {
        return Err(format!("Failed to create {}: {}", VLSILAB_DIR, e));
    }

    let launcher_script = r#"#!/bin/bash
# =============================================================================
#  EDA TOOL LAUNCHER  —  /opt/vlsilab/eda-launcher.sh
#  Auto-generated by vlsilab Ratatui Installer.
#  Author: snbhowmik [SRM IST Trichy]
# =============================================================================

export DISPLAY="${DISPLAY:-:0}"
export XAUTHORITY="${XAUTHORITY:-${HOME}/.Xauthority}"

# Combined license server configuration
export LM_LICENSE_FILE="2100@14.139.1.126:5280@14.139.1.126:27000@c2s.cdacb.in"
export XILINXD_LICENSE_FILE="2100@14.139.1.126:2100@c2s.cdacb.in"

# Silvaco & CADRE PATHs
export PATH="/opt/sedatools/bin:${PATH}"
export SFLM_FLEXLM=1
[[ -d "/opt/cadre/bin" ]] && export PATH="/opt/cadre/bin:${PATH}"

# Xilinx Lazy Loader
_vlsi_load_xilinx() {
    echo "[EDA] Loading Xilinx environment..."
    [[ -f "/opt/Xilinx/2025.2/Vivado/settings64.sh" ]] && source "/opt/Xilinx/2025.2/Vivado/settings64.sh"
    [[ -f "/opt/Xilinx/2025.2/Vitis/settings64.sh" ]]  && source "/opt/Xilinx/2025.2/Vitis/settings64.sh"
    unset -f vivado vitis xsct xsim xvlog model_composer source-xilinx _vlsi_load_xilinx
    echo "[EDA] Xilinx environment ready."
}
source-xilinx() { _vlsi_load_xilinx; }
vivado()         { _vlsi_load_xilinx && command vivado "$@"; }
vitis()          { _vlsi_load_xilinx && command vitis "$@"; }
xsct()           { _vlsi_load_xilinx && command xsct "$@"; }
xsim()           { _vlsi_load_xilinx && command xsim "$@"; }
xvlog()          { _vlsi_load_xilinx && command xvlog "$@"; }
model_composer() { _vlsi_load_xilinx && command model_composer "$@"; }

# Cadence Lazy Loader
_vlsi_load_cadence() {
    echo "[EDA] Loading Cadence environment..."
    export CADENCE_DIR="/opt/cadence"
    export PATH="${CADENCE_DIR}/IC618/bin:${CADENCE_DIR}/SPECTRE191/bin:${CADENCE_DIR}/GENUS211/bin:${PATH}"
    unset -f virtuoso spectre genus source-cadence _vlsi_load_cadence
    echo "[EDA] Cadence environment ready."
}
source-cadence() { _vlsi_load_cadence; }
virtuoso()       { _vlsi_load_cadence && command virtuoso "$@"; }
spectre()        { _vlsi_load_cadence && command spectre "$@"; }
genus()          { _vlsi_load_cadence && command genus "$@"; }
"#;

    if let Err(e) = fs::write(EDA_LAUNCHER, launcher_script) {
        return Err(format!("Failed to write {}: {}", EDA_LAUNCHER, e));
    }

    use std::os::unix::fs::PermissionsExt;
    let _ = fs::set_permissions(EDA_LAUNCHER, fs::Permissions::from_mode(0o755));

    // Update student user's .bashrc if present
    let student_bashrc = format!("/home/{}/.bashrc", config.student_user);
    if Path::new(&student_bashrc).exists() {
        let entry = "\n# Source VLSI Lab EDA Launcher\nif [ -f /opt/vlsilab/eda-launcher.sh ]; then\n    source /opt/vlsilab/eda-launcher.sh\nfi\n";
        if let Ok(content) = fs::read_to_string(&student_bashrc) {
            if !content.contains("/opt/vlsilab/eda-launcher.sh") {
                let _ = fs::write(&student_bashrc, format!("{}{}", content, entry));
                send_log(&tx, &format!("[SUCCESS] Sourced eda-launcher.sh in {}", student_bashrc));
            }
        }
    }

    send_log(&tx, "[SUCCESS] Created /opt/vlsilab/eda-launcher.sh");
    Ok(())
}

fn send_log(tx: &mpsc::UnboundedSender<String>, msg: &str) {
    tx.send(msg.to_string()).ok();
}
