use std::fs;
use std::path::Path;
use tokio::sync::mpsc;
use crate::installer::config::{CADENCE_ENV_FILE, EDA_LAUNCHER};

/// Canonical /opt/cadence/cadence-env.sh — mirrors the reference file shipped
/// at the repo root. Cadence needs every TOOL HOME on this list; a trimmed-down
/// version silently breaks tools that aren't referenced by name (Assura, Quantus,
/// PVS, Innovus, Xcelium, Jasper, etc.) because their PATH entries never get added.
const CADENCE_ENV_SCRIPT: &str = r#"#!/bin/bash
# =============================================================================
#  CADENCE TOOL ENVIRONMENT — AUTO-GENERATED BY the C2S Setup TUI
#  Author: snbhowmik
#
#  This script is sourced by /opt/vlsilab/eda-launcher.sh the first time a
#  Cadence binary is invoked (see _vlsi_load_cadence).
#  It uses _cds_add_path to only add directories that exist on disk,
#  keeping startup fast and preventing terminal crashes.
# =============================================================================

# Guard: don't load twice in the same shell
if [[ "${_CADENCE_ENV_LOADED:-}" == "1" ]]; then
    return 0 2>/dev/null || exit 0
fi


# ─────────────────────────────────────────────────────────────────────────────
# PATH HELPER — adds directories to PATH only if they exist
# ─────────────────────────────────────────────────────────────────────────────
_cds_add_path() {
    local dir
    for dir in "$@"; do
        [[ -d "$dir" ]] && export PATH="${dir}:${PATH}"
    done
}

# ─────────────────────────────────────────────────────────────────────────────
# BASE SETTINGS
# ─────────────────────────────────────────────────────────────────────────────
export CDS_Netlisting_Mode=Analog
export QRC_ENABLE_QRCRACTION="1"
export CDS_AUTO_64BIT=ALL
export CDS_AHDLCMI_ENABLE=YES
export EDITOR=gedit
export LANG=en_US

# ─────────────────────────────────────────────────────────────────────────────
# LICENSE
# ─────────────────────────────────────────────────────────────────────────────
export LM_LICENSE_FILE="5280@14.139.1.126"
export CDS_LIC_FILE="${LM_LICENSE_FILE}"

# ─────────────────────────────────────────────────────────────────────────────
# TOOL HOMES  — CIC (Custom IC)
# ─────────────────────────────────────────────────────────────────────────────
export LIBERATEHOME="/opt/cadence/LIBERATE201"

export CDSHOME="/opt/cadence/IC618"
export ASSURAHOME="/opt/cadence/ASSURA41"
export QRC_HOME="/opt/cadence/QUANTUS212"
export PVSHOME="/opt/cadence/PVS222"
export MMSIMHOME="/opt/cadence/SPECTRE211"

# ─────────────────────────────────────────────────────────────────────────────
# TOOL HOMES  — ASIC
# ─────────────────────────────────────────────────────────────────────────────
export IUSHOME="/opt/cadence/INCISIVE152" #not found
export LECHOME="/opt/cadence/CONFRML211"
export INNOVUSHOME="/opt/cadence/INNOVUS211"
export GENUSHOME="/opt/cadence/GENUS211"
export MODUSHOME="/opt/cadence/MODUS221"
export SSVHOME="/opt/cadence/SSV211"

# ─────────────────────────────────────────────────────────────────────────────
# TOOL HOMES  — ADDITIONAL
# ─────────────────────────────────────────────────────────────────────────────
export JASPERHOME="/opt/cadence/JASPER2209"
export MVSHOME="/opt/cadence/MVS211"
export SIGRITYHOME="/opt/cadence/SIGRITY20221"
export STRATUSHOME="/opt/cadence/STRATUS2202"
export PEGASUSHOME="/opt/cadence/PEGASUSDFM221"
export XCELIUMHOME="/opt/cadence/XCELIUM2209"
export ULTRASIMHOME="/opt/cadence/ULTRASIM181" #not found
export VMANAGERHOME="/opt/cadence/VMANAGER2209"
export INTEGRANDHOME="/opt/cadence/INTEGRAND63"
export JLSHOME="/opt/cadence/JLS211"

# ─────────────────────────────────────────────────────────────────────────────
# TOOL HOMES  — PCB
# ─────────────────────────────────────────────────────────────────────────────
export SPBHOME="/opt/cadence/SPB221"

# ─────────────────────────────────────────────────────────────────────────────
# FOUNDRY / LIBRARIES
# ─────────────────────────────────────────────────────────────────────────────
export FOUNDRY="/opt/cadence/FOUNDRY"
export ANALOG="${FOUNDRY}/analog"
export STDCELL="${FOUNDRY}/stdcell"
export FINFET="${FOUNDRY}/cds_ff_mpt_v_1.0"
export DIGITAL="${FOUNDRY}/digital"
export dig_45nm="${DIGITAL}/45nm"

# ─────────────────────────────────────────────────────────────────────────────
# DERIVED VARIABLES
# ─────────────────────────────────────────────────────────────────────────────
export CDS_INST_DIR="${CDSHOME}"
export AMSHOME="${IUSHOME}"

# LD_LIBRARY_PATH — only add existing directories
export LD_LIBRARY_PATH="${CDS_INST_DIR}/tools/lib:${CDS_INST_DIR}/tools/dfII/lib:${IUSHOME}/tools/lib:${LD_LIBRARY_PATH:-}"

# ─────────────────────────────────────────────────────────────────────────────
# PATH  — add tool bin directories (only if they exist on disk)
# ─────────────────────────────────────────────────────────────────────────────

# CIC tools
_cds_add_path \
    "${CDS_INST_DIR}/bin" "${CDS_INST_DIR}/tools/bin" \
    "${MMSIMHOME}/bin" \
    "${ASSURAHOME}/bin" "${ASSURAHOME}/tools/bin" "${ASSURAHOME}/tools/dfII/bin" \
    "${ASSURAHOME}/tools.lnx86/dfII/bin" "${ASSURAHOME}/share/bin" \
    "${PVSHOME}/bin" "${PVSHOME}/tools/bin" "${PVSHOME}/tools.lnx86/bin" \
    "${PVSHOME}/tools/dfII/bin" "${PVSHOME}/tools/assura/bin" \
    "${QRC_HOME}/tools/bin" \
    "${LIBERATEHOME}/bin" "${LIBERATEHOME}/tools.lnx86/bin" "${LIBERATEHOME}/tools.lnx86/dfII/bin"

# ASIC tools
_cds_add_path \
    "${IUSHOME}/bin" "${IUSHOME}/tools.lnx86/bin" "${IUSHOME}/tools/dfII/bin" \
    "${IUSHOME}/tools.lnx86/dfII/bin" "${IUSHOME}/share/bin" \
    "${LECHOME}/bin" "${LECHOME}/tools.lnx86/bin" "${LECHOME}/tools.lnx86/dfII/bin" \
    "${LECHOME}/share/bin" \
    "${GENUSHOME}/bin" "${GENUSHOME}/share/bin" "${GENUSHOME}/tools.lnx86/bin" \
    "${GENUSHOME}/tools.lnx86/dfII/bin" \
    "${INNOVUSHOME}/bin" "${INNOVUSHOME}/tools/bin" "${INNOVUSHOME}/tools/dfII/bin" \
    "${INNOVUSHOME}/share/bin" \
    "${SSVHOME}/bin" "${SSVHOME}/tools.lnx86/bin" "${SSVHOME}/tools.lnx86/dfII/bin" \
    "${SSVHOME}/share/bin" \
    "${MODUSHOME}/bin" "${MODUSHOME}/tools.lnx86/bin" "${MODUSHOME}/tools.lnx86/dfII/bin"

# Additional tools
_cds_add_path \
    "${XCELIUMHOME}/bin" "${XCELIUMHOME}/tools/bin" "${XCELIUMHOME}/tools.lnx86/bin" \
    "${XCELIUMHOME}/tools/dfII/bin" "${XCELIUMHOME}/tools.lnx86/dfII/bin" \
    "${XCELIUMHOME}/share/bin" \
    "${JASPERHOME}/bin" "${JASPERHOME}/tools.lnx86/bin" "${JASPERHOME}/tools.lnx86/dfII/bin" \
    "${JASPERHOME}/share/bin" \
    "${MVSHOME}/bin" "${MVSHOME}/tools.lnx86/bin" "${MVSHOME}/tools.lnx86/dfII/bin" \
    "${MVSHOME}/share/bin" \
    "${SIGRITYHOME}/bin" "${SIGRITYHOME}/tools.lnx86/bin" "${SIGRITYHOME}/tools.lnx86/dfII/bin" \
    "${SIGRITYHOME}/share/bin" \
    "${STRATUSHOME}/bin" "${STRATUSHOME}/tools.lnx86/bin" "${STRATUSHOME}/tools.lnx86/dfII/bin" \
    "${STRATUSHOME}/share/bin" \
    "${PEGASUSHOME}/bin" "${PEGASUSHOME}/tools.lnx86/bin" "${PEGASUSHOME}/tools.lnx86/dfII/bin" \
    "${PEGASUSHOME}/share/bin" \
    "${ULTRASIMHOME}/bin" "${ULTRASIMHOME}/tools.lnx86/bin" "${ULTRASIMHOME}/tools.lnx86/dfII/bin" \
    "${ULTRASIMHOME}/share/bin" \
    "${VMANAGERHOME}/bin" "${VMANAGERHOME}/tools.lnx86/bin" "${VMANAGERHOME}/tools.lnx86/dfII/bin" \
    "${VMANAGERHOME}/share/bin" \
    "${INTEGRANDHOME}/bin" "${INTEGRANDHOME}/tools.lnx86/bin" "${INTEGRANDHOME}/tools.lnx86/dfII/bin" \
    "${INTEGRANDHOME}/share/bin" \
    "${JLSHOME}/bin" "${JLSHOME}/tools.lnx86/bin" "${JLSHOME}/tools.lnx86/dfII/bin" \
    "${JLSHOME}/share/bin"

# PCB tools
_cds_add_path \
    "${SPBHOME}/bin" "${SPBHOME}/tools.lnx86/bin" "${SPBHOME}/tools.lnx86/pcb/bin" \
    "${SPBHOME}/tools.lnx86/dfII/bin"

# ─────────────────────────────────────────────────────────────────────────────
# MARK LOADED
# ─────────────────────────────────────────────────────────────────────────────
export _CADENCE_ENV_LOADED=1
"#;

/// Canonical /opt/vlsilab/eda-launcher.sh — mirrors the reference file shipped
/// at the repo root. This is the single script every user's .bashrc sources; it
/// stays cheap at shell startup and lazy-loads the heavy Cadence/Xilinx
/// environments only when one of their wrapper functions is actually invoked.
const EDA_LAUNCHER_SCRIPT: &str = r#"#!/bin/bash
# =============================================================================
#  EDA TOOL LAUNCHER  —  /opt/vlsilab/eda-launcher.sh
#  Auto-generated by the C2S Setup TUI. Do not edit manually.
#  Source: setup.sh (snbhowmik)
#
#  This file is sourced by .bashrc on every terminal open.
#  It only defines small wrapper functions — nothing heavy runs at startup.
#  Heavy environments (Xilinx, Cadence) load only when you call the tool.
#
#  How to use:
#    vivado        → loads Xilinx env, launches Vivado
#    vitis         → loads Xilinx env, launches Vitis
#    virtuoso      → loads Cadence env, launches Virtuoso
#    spectre       → loads Cadence env, launches Spectre
#    genus         → loads Cadence env, launches Genus
#    deckbuild     → Silvaco (always available — lightweight)
#    victory       → Silvaco (always available — lightweight)
#
#  To manually load an environment in the current shell:
#    source-xilinx     (then vivado, vitis, etc. work as normal binaries)
#    source-cadence    (then virtuoso, spectre, etc. work as normal binaries)
# =============================================================================

# ── X11 display — required by all EDA GUIs ───────────────────────────────────
# Set a sane default so tools work when launched from terminal.
# GDM is configured to use X11 (WaylandEnable=false in /etc/gdm/custom.conf).
export DISPLAY="${DISPLAY:-:0}"
export XAUTHORITY="${XAUTHORITY:-${HOME}/.Xauthority}"

# ── Combined license server — covers ALL tools ───────────────────────────────
# FlexLM connects to the correct port per tool. No conflicts.
export LM_LICENSE_FILE="2100@14.139.1.126:5280@14.139.1.126:27000@c2s.cdacb.in"
export XILINXD_LICENSE_FILE="2100@14.139.1.126:2100@c2s.cdacb.in"

# ── Silvaco — always-loaded (lightweight: 1 PATH + 2 exports) ────────────────
export PATH="/opt/sedatools/bin:${PATH}"
export SFLM_FLEXLM=1

# ── CADRE — always-loaded (lightweight: 1 PATH) ──────────────────────────────
[[ -d "/opt/cadre/bin" ]] && export PATH="/opt/cadre/bin:${PATH}"

# ── Xilinx — lazy loader ──────────────────────────────────────────────────────
# Nothing executes at shell startup. Env loads when you first type vivado/vitis.
_vlsi_load_xilinx() {
    echo "[EDA] Loading Xilinx 2025.2 environment..."
    [[ -f "/opt/Xilinx/2025.2/Vivado/settings64.sh"        ]] && source "/opt/Xilinx/2025.2/Vivado/settings64.sh"
    [[ -f "/opt/Xilinx/2025.2/Vitis/settings64.sh"         ]] && source "/opt/Xilinx/2025.2/Vitis/settings64.sh"
    [[ -f "/opt/Xilinx/2025.2/Model_Composer/settings64.sh" ]] && source "/opt/Xilinx/2025.2/Model_Composer/settings64.sh"
    [[ -f "/opt/Xilinx/2025.2/PDM/settings64.sh"           ]] && source "/opt/Xilinx/2025.2/PDM/settings64.sh"
    # Remove these wrappers — Xilinx binaries are now on PATH directly
    unset -f vivado vitis xsct xsim xvlog model_composer source-xilinx _vlsi_load_xilinx
    echo "[EDA] Xilinx environment ready."
}
# Manual loader alias (for when you want env without running a tool)
source-xilinx() { _vlsi_load_xilinx; }
# Wrapper functions — call the real binary after env loads
vivado()          { _vlsi_load_xilinx && command vivado "$@"; }
vitis()           { _vlsi_load_xilinx && command vitis "$@"; }
xsct()            { _vlsi_load_xilinx && command xsct "$@"; }
xsim()            { _vlsi_load_xilinx && command xsim "$@"; }
xvlog()           { _vlsi_load_xilinx && command xvlog "$@"; }
model_composer()  { _vlsi_load_xilinx && command model_composer "$@"; }

# ── Cadence — lazy loader ─────────────────────────────────────────────────────
# Nothing executes at shell startup. Env loads when you first type virtuoso/etc.
_vlsi_load_cadence() {
    echo "[EDA] Loading Cadence environment..."
    [[ -f "/opt/cadence/cadence-env.sh" ]] && source "/opt/cadence/cadence-env.sh"
    # Remove these wrappers — Cadence binaries are now on PATH directly
    unset -f virtuoso spectre genus innovus xcelium modus liberate pegasus              source-cadence _vlsi_load_cadence
    echo "[EDA] Cadence environment ready."
}
# Manual loader alias
source-cadence() { _vlsi_load_cadence; }
# Wrapper functions
virtuoso()  { _vlsi_load_cadence && command virtuoso "$@"; }
spectre()   { _vlsi_load_cadence && command spectre "$@"; }
genus()     { _vlsi_load_cadence && command genus "$@"; }
innovus()   { _vlsi_load_cadence && command innovus "$@"; }
xcelium()   { _vlsi_load_cadence && command xcelium "$@"; }
modus()     { _vlsi_load_cadence && command modus "$@"; }
liberate()  { _vlsi_load_cadence && command liberate "$@"; }
pegasus()   { _vlsi_load_cadence && command pegasus "$@"; }
"#;

pub async fn recreate_env(
    tool: &str,
    tx: mpsc::UnboundedSender<String>,
) -> Result<(), String> {
    match tool.to_lowercase().as_str() {
        "cadence" => {
            write_file(CADENCE_ENV_FILE, CADENCE_ENV_SCRIPT, 0o644)?;
            send_log(&tx, &format!("[SUCCESS] Wrote {}", CADENCE_ENV_FILE));
        }
        // Xilinx, Silvaco and CADRE are defined entirely inside the shared
        // eda-launcher.sh (lazy loader / always-loaded PATH respectively) —
        // there is no separate per-tool file to regenerate for them.
        "xilinx" | "silvaco" | "cadre" => {}
        _ => return Err(format!("Unknown tool: {}", tool)),
    }

    write_base_launcher(&tx)?;
    send_log(&tx, &format!("[SUCCESS] Refreshed environment for {}", tool));
    Ok(())
}

fn write_base_launcher(tx: &mpsc::UnboundedSender<String>) -> Result<(), String> {
    write_file(EDA_LAUNCHER, EDA_LAUNCHER_SCRIPT, 0o755)?;
    send_log(tx, "[SUCCESS] Refreshed base eda-launcher.sh");
    Ok(())
}

fn write_file(path: &str, contents: &str, mode: u32) -> Result<(), String> {
    if let Some(parent) = Path::new(path).parent() {
        fs::create_dir_all(parent).map_err(|e| format!("Failed to create {}: {}", parent.display(), e))?;
    }
    fs::write(path, contents).map_err(|e| format!("Failed to write {}: {}", path, e))?;
    use std::os::unix::fs::PermissionsExt;
    let _ = fs::set_permissions(path, fs::Permissions::from_mode(mode));
    Ok(())
}

fn send_log(tx: &mpsc::UnboundedSender<String>, msg: &str) {
    tx.send(msg.to_string()).ok();
}
